[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "chromadb>=1.4.1",
    "fastapi>=0.128.0",
    "gunicorn>=24.0.0",
    "lxml>=6.0.2",
    "lxml-stubs>=0.5.1",
    "numpy>=2.4.1",
    "openai>=2.15.0",
    "pandas>=3.0.0",
    "psycopg2>=2.9.11",
    "pydantic>=2.12.5",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.21",
    "rarfile>=4.2",
    "sqlalchemy>=2.0.46",
    "svix>=1.84.1",
    "uvicorn>=0.40.0",
]
